### ISSUE TITLE
Terminal coloring no longer works

### ISSUE THREAD

**Issue by Razican** [SUPERAndroidAnalyzer/super#159]
It seems that terminal coloring/formatting is not working since we fixed #126. It might be a cargo issue, since the dependencies are well specified and when we remove the Windows dependency, it works. This is the relevant `Cargo.toml` section:

```toml
[target.'cfg(windows)'.dependencies]
colored = { version = "1.6.0", features = ["no-color"] }

[target.'cfg(not(windows))'.dependencies]
colored = "1.6.0"
```
